# Generated by Django 3.2.6 on 2024-05-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_alter_product_countinstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price0',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
