# Generated by Django 3.2.6 on 2024-05-08 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_product_price0'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price0',
            new_name='priceOrigin',
        ),
    ]
