# Generated by Django 3.2.6 on 2024-05-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_price0_product_priceorigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='new_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
