# Generated by Django 3.2.6 on 2024-05-10 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_order_new_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='new_status',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
