# Generated by Django 3.2.6 on 2024-05-13 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0026_alter_order_new_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='numberSoldByDay',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='numberSoldByM',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='numberSoldByY',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='rateProduct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_rate_product', to='base.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='rateUser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_rate_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='statPaidD',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='statPaidM',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='statPaidY',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='topProductPaid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_top_product_paid', to='base.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='userBoughtHigh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_user_bought_high', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='userPaidMoneyHigh',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_user_paid_money_high', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='new_status',
            field=models.CharField(blank=True, default='đã nhận được đơn hàng', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
