# Generated by Django 3.2.6 on 2024-05-14 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0027_auto_20240514_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='numberSoldByDay',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numberSoldByM',
        ),
        migrations.RemoveField(
            model_name='order',
            name='numberSoldByY',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rateProduct',
        ),
        migrations.RemoveField(
            model_name='order',
            name='rateUser',
        ),
        migrations.RemoveField(
            model_name='order',
            name='statPaidD',
        ),
        migrations.RemoveField(
            model_name='order',
            name='statPaidM',
        ),
        migrations.RemoveField(
            model_name='order',
            name='statPaidY',
        ),
        migrations.RemoveField(
            model_name='order',
            name='topProductPaid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userBoughtHigh',
        ),
        migrations.RemoveField(
            model_name='order',
            name='userPaidMoneyHigh',
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statPaidD', models.IntegerField(null=True)),
                ('statPaidM', models.IntegerField(null=True)),
                ('statPaidY', models.IntegerField(null=True)),
                ('numberSoldByDay', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('numberSoldByM', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('numberSoldByY', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.order')),
                ('rateProduct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_rate_product', to='base.product')),
                ('rateUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_rate_user', to=settings.AUTH_USER_MODEL)),
                ('topProductPaid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_top_product_paid', to='base.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_user1', to=settings.AUTH_USER_MODEL)),
                ('userBoughtHigh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_user_bought_high', to=settings.AUTH_USER_MODEL)),
                ('userPaidMoneyHigh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_user_paid_money_high', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
