# Generated by Django 3.2.6 on 2024-05-16 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_auto_20240516_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='vnpay_transaction_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
