# Generated by Django 3.2.4 on 2024-05-22 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_order_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
    ]
